version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER_PASSWORD=${USER_PASSWORD}
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nn-admin
      - MONGO_INITDB_ROOT_PASSWORD=${USER_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
